### PR TITLE
Adding an article to week 02 of articles of the week

### PR DESCRIPTION
**Pull request by OscarKhaing**

### CODE REVIEW

**Comment by shanekim28** [comment]
LGTM, thanks for contributing! Before I approve, can you explain what the PR title "Adding an article to week 02 of articles of the week" means?

**Comment by OscarKhaing** [comment]
Edited chunk is Line 49-69 in new file BoardData.js; 
Commented out Old Tech Lead Ryan's info and updated to John's info;
IMPORTANT: I uploaded John's picture onto AWS cloud in the TESCPictures2022 folder as NewTechLead2022; 
Previous picture of Tech Lead is picture called TechLead2022 in the same folder in AWS cloud , which is a photo of Ryan;

**Comment by OscarKhaing** [comment]
I have no idea I think I just copy pasted code from a web tutorial when committing; will make sure to reflect name in later project edits;

**Comment by OscarKhaing** [comment]
^^Above comment is response to Shane's questions

Sorry it's my first time using this this is amazing LOL

**Review by DivyamRana007 — COMMENTED** [review]
- Change John's email ID : UCSD email id
- John's bio : Empty String
- Change Ryan's position to Co-President

**Pull request closed without merging**
