### PR TITLE
added existing sponsor logos

### PR DESCRIPTION
**Pull request by nik-dange**

### CODE REVIEW

**Comment by shanekim28** [comment]
Before I approve, I noticed the Leidos logo and General Atomics logo are monochromatic. Maybe there was an issue with conversion? Everything else looks good though

**Comment by nik-dange** [comment]
fixed leidos, thanks for catching it! I think it was an issue from jpeg to svg so I made it a png

As for general atomics, they provided an svg so I used that. Tried to switch it to a png but it looks the same

**Comment by shanekim28** [comment]
All good. Could you also add Keller North America?

**Comment by shanekim28** [comment]
> All good. Could you also add Keller North America?

Sorry, just saw it. LGTM!

**Review by shanekim28 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
